### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by waltdz** [WiWi33/Questing.lua#3]
Please help. I get this error as soon as I try running the questing.lua:

[3:11:30 PM] Error during the execution of 'onStart': MoonSharp.Interpreter.ScriptRuntimeException: attempt to index a nil value
   at PROBot.Utils.TaskUtils.CallActionWithTimeout(Action action, Action error, Int32 timeout)
   at PROBot.Scripting.LuaScript.CallFunction(String functionName, Object[] args)
   at PROBot.Scripting.LuaScript.CallFunctionSafe(String functionName, Object[] args)
[3:11:30 PM] Bot stopped

**Comment by waltdz** [comment]
Figured out problem thanks

**Comment by kingchenc** [comment]
how you fixxed it? for other users in the proshine forum with same problem, would be help your fix^^
